name: Deploy static site
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      BUCKET: ${{ secrets.S3_BUCKET }}
      DIST_ID: ${{ secrets.CF_DIST_ID }}
      REGION: ap-northeast-1

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ env.REGION }}

      - id: diff
        run: |
          aws s3 sync site/ s3://$BUCKET --delete --dryrun \
            | grep -E '^(upload:|delete:)' \
            | awk '{print "/"$4}' > list.txt || true
          echo "paths=$(tr '\n' ' ' < list.txt)" >> "$GITHUB_OUTPUT"
          echo "count=$(wc -l < list.txt)" >> "$GITHUB_OUTPUT"

      - run: aws s3 sync site/ s3://$BUCKET --delete

      - if: steps.diff.outputs.count != '0'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DIST_ID \
            --paths ${{ steps.diff.outputs.paths }}
