name: Deploy static site to S3 & CloudFront

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    # よく使う値は環境変数へ
    env:
      BUCKET: ${{ secrets.S3_BUCKET }}
      DIST_ID: ${{ secrets.CF_DIST_ID }}
      REGION: ${{ secrets.REGION }}
      ROLE_ARN: ${{ secrets.ROLE_ARN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dist
        run: |
          rm -rf dist
          mkdir -p dist/css dist/img dist/js
          cp index.html dist/
          [ -d css ] && cp -r css/* dist/css/
          [ -d img ] && cp -r img/* dist/img/
          [ -d js ] && cp -r js/* dist/js/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync dist/ s3://$BUCKET --delete

      - name: Invalidate specific paths
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DIST_ID \
            --paths "/index.html" "/css/*" "/js/*"
